version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lovelink_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: lovelink_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lovelink_net

  redis:
    image: redis:7
    container_name: lovelink_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lovelink_net

volumes:
  postgres_data:
  redis_data:

networks:
  lovelink_net:
    driver: bridge
